import type { Metadata } from "next"
import { Source_Code_Pro } from "next/font/google"
import { twSum } from "@/utils/utils"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import "./globals.css"

const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  weight: ["200", "400", "800"],
  style: ["normal", "italic"],
})

export const metadata: Metadata = {
  title: "Bruno M - Full-stack Developer",
  description: "Generated by create next app",
  authors: { name: "Bruno Mistro", url: "https://brunomistro.dev" },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={twSum(
          sourceCodePro.className,
          "flex h-full flex-col bg-gray-800 text-slate-50",
        )}
      >
        <Navbar />
        <main className="flex-auto">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
