import type { Metadata } from "next"
import { Source_Code_Pro } from "next/font/google"
import Navbar from "@/components/Navbar"
import "./globals.css"
import Footer from "@/components/Footer"

const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  weight: ["200", "400", "800"],
  style: ["normal", "italic"],
})

// text slate-50
// bg-color-gray-600
// sky-400
// sky-800
// yellow-400

export const metadata: Metadata = {
  title: "Bruno M - Full-stack Developer",
  description: "Generated by create next app",
  authors: { name: "Bruno Mistro", url: "https://brunomistro.dev" },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${sourceCodePro.className} flex h-full flex-col bg-gray-800 text-slate-50`}
      >
        <Navbar />
        <main className="flex-auto">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
