import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// edit font to source code pro
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-800 text-slate-50`}>
        {/* navbar */}
        {/* content */}
        <main>{children}</main>
        {/* footer */}
      </body>
    </html>
  );
}
